/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f746xx.h"
#include "reg_util.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClockSetup (void);


int main(void)
{
	SystemClockSetup();
    /* Loop forever */
	for(;;);
}


void SystemClockSetup(void)
{
    RCC_TypeDef *pRCC = RCC;

    /* Disable the main PLL */
    REG_CLR_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
    while (REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos)) {}

    /* Disable PLLSAI */
    REG_CLR_BIT(pRCC->CR, RCC_CR_PLLSAION_Pos);
    while (REG_READ_BIT(pRCC->CR, RCC_CR_PLLSAIRDY_Pos)) {}

    /* Enable HSE and wait until it is ready */
    REG_SET_BIT(pRCC->CR, RCC_CR_HSEON_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_HSERDY_Pos)) {}

    /* Select HSE as the PLL clock source */
    REG_SET_BIT(pRCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_Pos);

    /* PLLM = 25: 25 MHz / 25 = 1 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        25,
        0x3F,
        RCC_PLLCFGR_PLLM_Pos
    );

    /* PLLN = 432: 1 MHz * 432 = 432 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        432,
        0x1FF,
        RCC_PLLCFGR_PLLN_Pos
    );

    /* PLLP = 00: 432 MHz / 2 = 216 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        0,
        0x03,
        RCC_PLLCFGR_PLLP_Pos
    );

    /* PLLSAIN = 192: 1 MHz * 192 = 192 MHz */
    REG_SET_VAL(
        pRCC->PLLSAICFGR,
        192,
        0x1FF,
        RCC_PLLSAICFGR_PLLSAIN_Pos
    );

    /* PLLSAIR = 5: 192 MHz / 5 = 38.4 MHz */
    REG_SET_VAL(
        pRCC->PLLSAICFGR,
        5,
        0x07,
        RCC_PLLSAICFGR_PLLSAIR_Pos
    );

    /* PLLSAIDIVR = 01: 38.4 MHz / 4 = 9.6 MHz */
    REG_SET_VAL(
        pRCC->DCKCFGR1,
        1,
        0x03,
        RCC_DCKCFGR1_PLLSAIDIVR_Pos
    );

    /* Enable the main PLL */
    REG_SET_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos)) {}

    /* Enable PLLSAI */
    REG_SET_BIT(pRCC->CR, RCC_CR_PLLSAION_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_PLLSAIRDY_Pos)) {}
}
