/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdint.h>
#include "stm32f746xx.h"
#include "reg_util.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClockSetup (void);
void MCO1_Init        (void);


int main(void)
{
	SystemClockSetup();
    /* Loop forever */
	//MCO1_Init();
	for(;;);
}


void SystemClockSetup(void)
{
    RCC_TypeDef *pRCC = RCC;

    /* Disable the main PLL */
    REG_CLR_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
    while (REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos)) {}

    /* Disable PLLSAI */
    REG_CLR_BIT(pRCC->CR, RCC_CR_PLLSAION_Pos);
    while (REG_READ_BIT(pRCC->CR, RCC_CR_PLLSAIRDY_Pos)) {}

    /* Enable HSE and wait until it is ready */
    REG_SET_BIT(pRCC->CR, RCC_CR_HSEON_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_HSERDY_Pos)) {}

    /* Select HSE as the PLL clock source */
    REG_SET_BIT(pRCC->PLLCFGR, RCC_PLLCFGR_PLLSRC_Pos);

    /* PLLM = 25: 25 MHz / 25 = 1 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        25,
        0x3F,
        RCC_PLLCFGR_PLLM_Pos
    );

    /* PLLN = 432: 1 MHz * 432 = 432 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        432,
        0x1FF,
        RCC_PLLCFGR_PLLN_Pos
    );

    /* PLLP = 00: 432 MHz / 2 = 216 MHz */
    REG_SET_VAL(
        pRCC->PLLCFGR,
        0,
        0x03,
        RCC_PLLCFGR_PLLP_Pos
    );

    /* PLLSAIN = 192: 1 MHz * 192 = 192 MHz */
    REG_SET_VAL(
        pRCC->PLLSAICFGR,
        192,
        0x1FF,
        RCC_PLLSAICFGR_PLLSAIN_Pos
    );

    /* PLLSAIR = 5: 192 MHz / 5 = 38.4 MHz */
    REG_SET_VAL(
        pRCC->PLLSAICFGR,
        5,
        0x07,
        RCC_PLLSAICFGR_PLLSAIR_Pos
    );

    /* PLLSAIDIVR = 01: 38.4 MHz / 4 = 9.6 MHz */
    REG_SET_VAL(
        pRCC->DCKCFGR1,
        1,
        0x03,
        RCC_DCKCFGR1_PLLSAIDIVR_Pos
    );

    /* HPRE = 0000: AHB clock = SYSCLK / 1 = 216 MHz */
    REG_SET_VAL(
        pRCC->CFGR,
        0x00,
        0x0F,
        RCC_CFGR_HPRE_Pos
    );

    /* PPRE1 = 101: APB1 clock = HCLK / 4 = 54 MHz */
    REG_SET_VAL(
        pRCC->CFGR,
        0x05,
        0x07,
        RCC_CFGR_PPRE1_Pos
    );

    /* PPRE2 = 100: APB2 clock = HCLK / 2 = 108 MHz */
    REG_SET_VAL(
        pRCC->CFGR,
        0x04,
        0x07,
        RCC_CFGR_PPRE2_Pos
    );

    /* Enable the main PLL */
    REG_SET_BIT(pRCC->CR, RCC_CR_PLLON_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_PLLRDY_Pos)) {}

    /* Enable PLLSAI */
    REG_SET_BIT(pRCC->CR, RCC_CR_PLLSAION_Pos);
    while (!REG_READ_BIT(pRCC->CR, RCC_CR_PLLSAIRDY_Pos)) {}

    /* Enable the PWR peripheral clock */
    REG_SET_BIT(pRCC->APB1ENR, RCC_APB1ENR_PWREN_Pos);

    /* Configure Voltage Scale 1 */
    REG_SET_VAL(
        PWR->CR1,
        0x03,
        0x03,
        PWR_CR1_VOS_Pos
    );

    /* Enable Over-drive mode */
    REG_SET_BIT(PWR->CR1, PWR_CR1_ODEN_Pos);
    while (!REG_READ_BIT(PWR->CSR1, PWR_CSR1_ODRDY_Pos)) {}

    /* Enable Over-drive switching */
    REG_SET_BIT(PWR->CR1, PWR_CR1_ODSWEN_Pos);
    while (!REG_READ_BIT(PWR->CSR1, PWR_CSR1_ODSWRDY_Pos)) {}

    /* Configure Flash latency for 216 MHz */
    REG_SET_VAL(
        FLASH->ACR,
        7,
        0x0F,
        FLASH_ACR_LATENCY_Pos
    );

    while (((FLASH->ACR >> FLASH_ACR_LATENCY_Pos) & 0x0FU) != 7U) {}

    /* Enable Flash prefetch */
    REG_SET_BIT(
        FLASH->ACR,
        FLASH_ACR_PRFTEN_Pos
    );

    /* Enable ART accelerator */
    REG_SET_BIT(
        FLASH->ACR,
        FLASH_ACR_ARTEN_Pos
    );

    /* Select PLL as the system clock source */
    REG_SET_VAL(
        pRCC->CFGR,
        0x02,
        0x03,
        RCC_CFGR_SW_Pos
    );

    /* Wait until PLL is used as the system clock source */
    while (((pRCC->CFGR >> RCC_CFGR_SWS_Pos) & 0x03U) != 0x02U) {}
}

void MCO1_Init(void)
{
    RCC_TypeDef  *pRCC   = RCC;
    GPIO_TypeDef *pGPIOA = GPIOA;

    /* Enable GPIOA peripheral clock */
    REG_SET_BIT(
        pRCC->AHB1ENR,
        RCC_AHB1ENR_GPIOAEN_Pos
    );

    (void)pRCC->AHB1ENR;

    /*
     * Configure PA8 as Alternate Function mode.
     * MODER8 = 10
     */
    REG_SET_VAL(
        pGPIOA->MODER,
        0x02U,
        0x03U,
        GPIO_MODER_MODER8_Pos
    );

    /* Configure PA8 as push-pull */
    REG_CLR_BIT(
        pGPIOA->OTYPER,
        GPIO_OTYPER_OT8_Pos
    );

    /* Configure PA8 for very high output speed */
    REG_SET_VAL(
        pGPIOA->OSPEEDR,
        0x03U,
        0x03U,
        GPIO_OSPEEDR_OSPEEDR8_Pos
    );

    /* Disable pull-up and pull-down */
    REG_SET_VAL(
        pGPIOA->PUPDR,
        0x00U,
        0x03U,
        GPIO_PUPDR_PUPDR8_Pos
    );

    /*
     * Select AF0 for  .
     * PA8 is located in AFR[1], bits [3:0].
     * AF0 on PA8 is MCO1.
     */
    REG_SET_VAL(
        pGPIOA->AFR[1],
        0x00U,
        0x0FU,
        0U
    );

    /*
     * Select PLL clock as MCO1 source.
     *
     * MCO1[1:0]:
     * 00 - HSI
     * 01 - LSE
     * 10 - HSE
     * 11 - PLL
     */
    REG_SET_VAL(
        pRCC->CFGR,
        0x03U,
        0x03U,
        RCC_CFGR_MCO1_Pos
    );

    /*
     * MCO1PRE = 110: divide by 4.
     *
     * PLL clock = SYSCLK = 216 MHz
     * MCO1 = 216 MHz / 4 = 54 MHz
     */
    REG_SET_VAL(
        pRCC->CFGR,
        0x06U,
        0x07U,
        RCC_CFGR_MCO1PRE_Pos
    );
}

